//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMyPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGiamGia
    {
        public int MaGiamGia { get; set; }
        public string GiamGia { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauGiamGia { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThucGiamGia { get; set; }
        public Nullable<int> MucGiamGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TenGiamGia { get; set; }
    }
}
